// Generated by CoffeeScript 1.3.3

$(function() {
  var getSolved, looper, user_template, users;
  getSolved = function(username, callback) {
    var API_URL, request_url;
    API_URL = "http://judge.u-aizu.ac.jp/onlinejudge/webservice/user?id=";
    request_url = API_URL + username;
    $.ajax({
      url: request_url,
      type: "get",
      dataType: "xml",
      success: function(xml, status) {
        var solved, uname;
        uname = $(xml).find("user > id").text();
        solved = $(xml).find("user > id > solved").text();
        return callback(uname, solved, status);
      }
    });
    return 0;
  };
  users = ["raimei10130", "kagamiz", "orisano", "li_saku", "marin72_com", "shogo1996"];
  user_template = _.template("<tr><td><%= name %></td><td><%= solved %></td></tr>");
  looper = null;
  looper = function(ready_user, processed_user, callback) {
    var uname;
    if (ready_user.length === 0) {
      return callback(processed_user);
    } else {
      uname = ready_user.shift();
      return getSolved(uname, function(name, solve, status) {
        processed_user.push({
          uname: name,
          solved: solve
        });
        return looper(ready_user, processed_user, callback);
      });
    }
  };
  return looper(users, [], function(ulist) {
    var context;
    context = document.getElementById("solved-graph").getContext("2d");
    ulist.sort(function(a, b) {
      if (a.solved === b.solved) {
        return a.uname < b.uname;
      }
      return a.solved < b.solved;
    });
    _.each(ulist, function(item) {
      return $("table#watch-table").append(user_template(item));
    });
    return new Chart(context).Bar({
      labels: _.map(ulist, function(usr) {
        return usr.uname;
      }),
      datasets: [
        {
          data: _.map(ulist, function(usr) {
            return usr.solved;
          })
        }
      ]
    });
  });
});
